name = "electri-phi-handbook"
main = "src/index.ts"
compatibility_date = "2026-09-21"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "electri-phi-handbook"
database_id = "5b463fdd-9e69-415a-b7ee-f2cf38e8dcdf"
migrations_dir = "migrations"
